#!/usr/bin/env python3
"""Check if credentials match and provide troubleshooting info."""

from app.core.config import get_settings

get_settings.cache_clear()
settings = get_settings()

print("=" * 60)
print("Credentials Check")
print("=" * 60)
print()
print("Current .env values:")
print(f"  Client ID: {settings.gmail_client_id}")
print(f"  Client Secret: {settings.gmail_client_secret[:20]}...")
print(f"  Refresh Token: {settings.gmail_refresh_token[:40]}...")
print(f"  User Email: {settings.gmail_user_email}")
print()
print("=" * 60)
print("Troubleshooting:")
print("=" * 60)
print()
print("If refresh token doesn't work, the most common causes are:")
print()
print("1. Client ID/Secret mismatch:")
print("   → Refresh token must be obtained with the SAME Client ID/Secret")
print("   → Check if .env has the exact same values as OAuth Playground")
print()
print("2. Token was revoked or expired:")
print("   → Get a new refresh token")
print()
print("3. Wrong application type:")
print("   → Web application tokens work, but need matching credentials")
print()
print("=" * 60)
print("Solution:")
print("=" * 60)
print()
print("Option A: Use OAuth Playground")
print("  1. Go to https://developers.google.com/oauthplayground/")
print("  2. Settings → Use your own OAuth credentials")
print("  3. Enter your Client ID and Client Secret from Google Cloud Console")
print("  4. Select scope: https://www.googleapis.com/auth/gmail.readonly")
print("  5. Authorize → Exchange → Copy refresh token")
print()
print("Option B: Use the script (recommended)")
print("  1. Set GMAIL_CLIENT_ID and GMAIL_CLIENT_SECRET in .env or environment")
print("  2. Run: poetry run python get_refresh_token.py")
print("  3. Or run without env vars - script will prompt for credentials")
print()

